### ISSUE TITLE
Add scheduling support

### ISSUE THREAD

**Issue by OperationXen** [OperationXen/InvisibleServant#10]
Add automatic job to auto-post games to channel at release time

**Comment by MykeMyke** [comment]
Batch release. What is the simplest way to assign a pending game to a batch, and assign a date (future only) to a batch? Is this doable in Django?

**Comment by MykeMyke** [comment]
![image](https://user-images.githubusercontent.com/72384771/148084144-1d555106-43d7-4942-9901-da0bc8f52e95.png)
