### ISSUE TITLE
Send to calendar

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/InvisibleServant#16]
Add button to send to Google/Outlook/Apple Calendar

**Comment by OperationXen** [comment]
This likely needs to be three buttons, what I might do instead is add an "add to calendar" button which PMs you all of he relevant links

**Comment by MykeMyke** [comment]
Perfect

**Comment by OperationXen** [comment]
I've added the skeleton of this feature and got it working with google calendar, but don't have an apple or outlook account to use to do those two link types, as a result this would be a good issue for someone else to try

**Comment by OperationXen** [comment]
The functionality is in "CoreServer\discordbot\utils\format.py"

**Comment by MykeMyke** [comment]
Rgr - will look to source support
