### ISSUE TITLE
Add limit to active concurrent signups

### ISSUE THREAD

**Issue by MykeMyke** [OperationXen/InvisibleServant#17]
Limit number of max active concurrent signups allowed based on role.

**Comment by OperationXen** [comment]
> 

Does this treat waitlisting the same as confirmed slots?

**Comment by MykeMyke** [comment]
Interesting question - tentatively I think Yes, which will limit the total volume of signups more (therefore rationing capacity more severely), and we adjust values in order to get to where we want to be. However, it's a significant enough question that I think I'll ask the Council on Triden and get back to you with a definitive answer - because you would be pissed if you happened to not get any games because you didn't make it through the waitlist...

**Comment by MykeMyke** [comment]
Confirmed - We will include waitlist spots in signup limits.

**Comment by OperationXen** [comment]
I'll make the values editable and start off with some defaults which I'm pulling out of thin air:

2 for gen-pop, 5 for wanderer, 8 for jester, 10 for knight and 20 for sage?

**Comment by MykeMyke** [comment]
I'm not sure on the implementation, but I would have thought that only specified roles would require numbers right? So I don't think gen-pop is required, or is that just for future proofing?

I would run with:
0 for gen pop
2 for Traveller
4 for Jester
4 for Resident DM, Moderator, Treasurer, Admin
8 for Knight
12 for Sage

If this is editable on a simple Django panel in the future then so much the better!

**Comment by OperationXen** [comment]
Ok, I can make the values editable, but the order is going to be fixed, if you want to add or remove a rank it's going to be a code edit

**Comment by OperationXen** [comment]
Alright, cancel that last - I've worked out an elegant approach
