### ISSUE TITLE
Add ban lookup

### ISSUE THREAD

**Issue by OperationXen** [OperationXen/InvisibleServant#7]

**Comment by MykeMyke** [comment]
Soft / hard bans, time bounded as discussed.

Is it possible to also have strikes / warnings recorded by the same method? Then auto-convert 3 strikes into a soft ban for example?

**Comment by OperationXen** [comment]
Yes, how long do you want strikes to remain current for before they drop off?

**Comment by MykeMyke** [comment]
12 months (though I'd like that to be a setting in the admin panel for future proofing!) - we also need to rescind / pardon / revoke a strike.
